services:
  - type: web
    name: coffee-brewing-optimizer-backend
    runtime: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    plan: free
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLAUDE_API_KEY
        sync: false